# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSamplingDetails.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddSamplingDetails(object):
    def setupUi(self, DialogAddSamplingDetails):
        DialogAddSamplingDetails.setObjectName("DialogAddSamplingDetails")
        DialogAddSamplingDetails.resize(350, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogAddSamplingDetails.sizePolicy().hasHeightForWidth())
        DialogAddSamplingDetails.setSizePolicy(sizePolicy)
        DialogAddSamplingDetails.setMinimumSize(QtCore.QSize(350, 300))
        DialogAddSamplingDetails.setMaximumSize(QtCore.QSize(350, 300))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        DialogAddSamplingDetails.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ImageIcons/Icons/AddRowIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogAddSamplingDetails.setWindowIcon(icon)
        DialogAddSamplingDetails.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        DialogAddSamplingDetails.setModal(False)
        self.groupBoxLocation = QtWidgets.QGroupBox(DialogAddSamplingDetails)
        self.groupBoxLocation.setGeometry(QtCore.QRect(0, 0, 350, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxLocation.sizePolicy().hasHeightForWidth())
        self.groupBoxLocation.setSizePolicy(sizePolicy)
        self.groupBoxLocation.setMinimumSize(QtCore.QSize(350, 60))
        self.groupBoxLocation.setMaximumSize(QtCore.QSize(350, 50))
        self.groupBoxLocation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBoxLocation.setObjectName("groupBoxLocation")
        self.labelStory = QtWidgets.QLabel(self.groupBoxLocation)
        self.labelStory.setGeometry(QtCore.QRect(190, 30, 30, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStory.sizePolicy().hasHeightForWidth())
        self.labelStory.setSizePolicy(sizePolicy)
        self.labelStory.setMinimumSize(QtCore.QSize(30, 25))
        self.labelStory.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelStory.setFont(font)
        self.labelStory.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStory.setObjectName("labelStory")
        self.labelLevel = QtWidgets.QLabel(self.groupBoxLocation)
        self.labelLevel.setGeometry(QtCore.QRect(75, 30, 30, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLevel.sizePolicy().hasHeightForWidth())
        self.labelLevel.setSizePolicy(sizePolicy)
        self.labelLevel.setMinimumSize(QtCore.QSize(30, 25))
        self.labelLevel.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelLevel.setFont(font)
        self.labelLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLevel.setObjectName("labelLevel")
        self.lineEditStory = QtWidgets.QLineEdit(self.groupBoxLocation)
        self.lineEditStory.setGeometry(QtCore.QRect(120, 30, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditStory.sizePolicy().hasHeightForWidth())
        self.lineEditStory.setSizePolicy(sizePolicy)
        self.lineEditStory.setMinimumSize(QtCore.QSize(70, 25))
        self.lineEditStory.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditStory.setFont(font)
        self.lineEditStory.setObjectName("lineEditStory")
        self.lineEditLevel = QtWidgets.QLineEdit(self.groupBoxLocation)
        self.lineEditLevel.setGeometry(QtCore.QRect(10, 30, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLevel.sizePolicy().hasHeightForWidth())
        self.lineEditLevel.setSizePolicy(sizePolicy)
        self.lineEditLevel.setMinimumSize(QtCore.QSize(70, 25))
        self.lineEditLevel.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditLevel.setFont(font)
        self.lineEditLevel.setObjectName("lineEditLevel")
        self.labelElement = QtWidgets.QLabel(self.groupBoxLocation)
        self.labelElement.setGeometry(QtCore.QRect(310, 30, 30, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelElement.sizePolicy().hasHeightForWidth())
        self.labelElement.setSizePolicy(sizePolicy)
        self.labelElement.setMinimumSize(QtCore.QSize(30, 25))
        self.labelElement.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelElement.setFont(font)
        self.labelElement.setAlignment(QtCore.Qt.AlignCenter)
        self.labelElement.setObjectName("labelElement")
        self.comboBoxElement = QtWidgets.QComboBox(self.groupBoxLocation)
        self.comboBoxElement.setGeometry(QtCore.QRect(240, 30, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxElement.sizePolicy().hasHeightForWidth())
        self.comboBoxElement.setSizePolicy(sizePolicy)
        self.comboBoxElement.setMinimumSize(QtCore.QSize(70, 25))
        self.comboBoxElement.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxElement.setFont(font)
        self.comboBoxElement.setEditable(False)
        self.comboBoxElement.setCurrentText("")
        self.comboBoxElement.setObjectName("comboBoxElement")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.setItemText(0, "")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.comboBoxElement.addItem("")
        self.groupBoxSamplingDate = QtWidgets.QGroupBox(DialogAddSamplingDetails)
        self.groupBoxSamplingDate.setGeometry(QtCore.QRect(0, 70, 350, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSamplingDate.sizePolicy().hasHeightForWidth())
        self.groupBoxSamplingDate.setSizePolicy(sizePolicy)
        self.groupBoxSamplingDate.setMinimumSize(QtCore.QSize(350, 60))
        self.groupBoxSamplingDate.setMaximumSize(QtCore.QSize(350, 50))
        self.groupBoxSamplingDate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBoxSamplingDate.setObjectName("groupBoxSamplingDate")
        self.comboBoxYear = QtWidgets.QComboBox(self.groupBoxSamplingDate)
        self.comboBoxYear.setGeometry(QtCore.QRect(30, 30, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxYear.sizePolicy().hasHeightForWidth())
        self.comboBoxYear.setSizePolicy(sizePolicy)
        self.comboBoxYear.setMinimumSize(QtCore.QSize(70, 25))
        self.comboBoxYear.setMaximumSize(QtCore.QSize(70, 25))
        self.comboBoxYear.setMaxVisibleItems(5)
        self.comboBoxYear.setObjectName("comboBoxYear")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxYear.addItem("")
        self.comboBoxMount = QtWidgets.QComboBox(self.groupBoxSamplingDate)
        self.comboBoxMount.setEnabled(False)
        self.comboBoxMount.setGeometry(QtCore.QRect(120, 30, 50, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMount.sizePolicy().hasHeightForWidth())
        self.comboBoxMount.setSizePolicy(sizePolicy)
        self.comboBoxMount.setMinimumSize(QtCore.QSize(50, 25))
        self.comboBoxMount.setMaximumSize(QtCore.QSize(50, 25))
        self.comboBoxMount.setMaxVisibleItems(5)
        self.comboBoxMount.setObjectName("comboBoxMount")
        self.comboBoxMount.addItem("")
        self.comboBoxDay = QtWidgets.QComboBox(self.groupBoxSamplingDate)
        self.comboBoxDay.setEnabled(False)
        self.comboBoxDay.setGeometry(QtCore.QRect(190, 30, 50, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDay.sizePolicy().hasHeightForWidth())
        self.comboBoxDay.setSizePolicy(sizePolicy)
        self.comboBoxDay.setMinimumSize(QtCore.QSize(50, 25))
        self.comboBoxDay.setMaximumSize(QtCore.QSize(50, 25))
        self.comboBoxDay.setObjectName("comboBoxDay")
        self.comboBoxDay.addItem("")
        self.groupBoxMaterialProperties = QtWidgets.QGroupBox(DialogAddSamplingDetails)
        self.groupBoxMaterialProperties.setGeometry(QtCore.QRect(0, 140, 350, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMaterialProperties.sizePolicy().hasHeightForWidth())
        self.groupBoxMaterialProperties.setSizePolicy(sizePolicy)
        self.groupBoxMaterialProperties.setMinimumSize(QtCore.QSize(350, 100))
        self.groupBoxMaterialProperties.setMaximumSize(QtCore.QSize(350, 100))
        self.groupBoxMaterialProperties.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBoxMaterialProperties.setObjectName("groupBoxMaterialProperties")
        self.comboBoxCementType = QtWidgets.QComboBox(self.groupBoxMaterialProperties)
        self.comboBoxCementType.setGeometry(QtCore.QRect(170, 65, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCementType.sizePolicy().hasHeightForWidth())
        self.comboBoxCementType.setSizePolicy(sizePolicy)
        self.comboBoxCementType.setMinimumSize(QtCore.QSize(60, 25))
        self.comboBoxCementType.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.comboBoxCementType.setFont(font)
        self.comboBoxCementType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxCementType.setObjectName("comboBoxCementType")
        self.comboBoxCementType.addItem("")
        self.comboBoxCementType.setItemText(0, "")
        self.comboBoxCementType.addItem("")
        self.comboBoxCementType.addItem("")
        self.comboBoxCementType.addItem("")
        self.comboBoxCementType.addItem("")
        self.comboBoxCementType.addItem("")
        self.label_fc = QtWidgets.QLabel(self.groupBoxMaterialProperties)
        self.label_fc.setGeometry(QtCore.QRect(240, 30, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fc.sizePolicy().hasHeightForWidth())
        self.label_fc.setSizePolicy(sizePolicy)
        self.label_fc.setMinimumSize(QtCore.QSize(100, 25))
        self.label_fc.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_fc.setFont(font)
        self.label_fc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fc.setObjectName("label_fc")
        self.lineEdit_fc = QtWidgets.QLineEdit(self.groupBoxMaterialProperties)
        self.lineEdit_fc.setGeometry(QtCore.QRect(170, 30, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fc.sizePolicy().hasHeightForWidth())
        self.lineEdit_fc.setSizePolicy(sizePolicy)
        self.lineEdit_fc.setMinimumSize(QtCore.QSize(60, 25))
        self.lineEdit_fc.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_fc.setFont(font)
        self.lineEdit_fc.setObjectName("lineEdit_fc")
        self.labelCementType = QtWidgets.QLabel(self.groupBoxMaterialProperties)
        self.labelCementType.setGeometry(QtCore.QRect(240, 65, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCementType.sizePolicy().hasHeightForWidth())
        self.labelCementType.setSizePolicy(sizePolicy)
        self.labelCementType.setMinimumSize(QtCore.QSize(100, 25))
        self.labelCementType.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCementType.setFont(font)
        self.labelCementType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCementType.setObjectName("labelCementType")
        self.labelUnit = QtWidgets.QLabel(self.groupBoxMaterialProperties)
        self.labelUnit.setGeometry(QtCore.QRect(50, 30, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUnit.sizePolicy().hasHeightForWidth())
        self.labelUnit.setSizePolicy(sizePolicy)
        self.labelUnit.setMinimumSize(QtCore.QSize(120, 25))
        self.labelUnit.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelUnit.setFont(font)
        self.labelUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnit.setObjectName("labelUnit")
        self.labelType = QtWidgets.QLabel(self.groupBoxMaterialProperties)
        self.labelType.setGeometry(QtCore.QRect(40, 65, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelType.sizePolicy().hasHeightForWidth())
        self.labelType.setSizePolicy(sizePolicy)
        self.labelType.setMinimumSize(QtCore.QSize(120, 25))
        self.labelType.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelType.setFont(font)
        self.labelType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelType.setObjectName("labelType")
        self.pushButtonCreateSampling = QtWidgets.QPushButton(DialogAddSamplingDetails)
        self.pushButtonCreateSampling.setGeometry(QtCore.QRect(65, 255, 100, 25))
        self.pushButtonCreateSampling.setObjectName("pushButtonCreateSampling")
        self.pushButtonCancelSampling = QtWidgets.QPushButton(DialogAddSamplingDetails)
        self.pushButtonCancelSampling.setGeometry(QtCore.QRect(185, 255, 100, 25))
        self.pushButtonCancelSampling.setObjectName("pushButtonCancelSampling")

        self.retranslateUi(DialogAddSamplingDetails)
        QtCore.QMetaObject.connectSlotsByName(DialogAddSamplingDetails)

    def retranslateUi(self, DialogAddSamplingDetails):
        _translate = QtCore.QCoreApplication.translate
        DialogAddSamplingDetails.setWindowTitle(_translate("DialogAddSamplingDetails", "نمونه گیری"))
        self.groupBoxLocation.setTitle(_translate("DialogAddSamplingDetails", "محل نمونه گیری"))
        self.labelStory.setText(_translate("DialogAddSamplingDetails", "طبقه"))
        self.labelLevel.setText(_translate("DialogAddSamplingDetails", "تراز"))
        self.labelElement.setText(_translate("DialogAddSamplingDetails", "االمان"))
        self.comboBoxElement.setItemText(1, _translate("DialogAddSamplingDetails", "فونداسیون"))
        self.comboBoxElement.setItemText(2, _translate("DialogAddSamplingDetails", "تیر"))
        self.comboBoxElement.setItemText(3, _translate("DialogAddSamplingDetails", "ستون"))
        self.comboBoxElement.setItemText(4, _translate("DialogAddSamplingDetails", "دیوار برشی"))
        self.comboBoxElement.setItemText(5, _translate("DialogAddSamplingDetails", "دیوار حائل"))
        self.comboBoxElement.setItemText(6, _translate("DialogAddSamplingDetails", "کف"))
        self.comboBoxElement.setItemText(7, _translate("DialogAddSamplingDetails", "راه پله"))
        self.comboBoxElement.setItemText(8, _translate("DialogAddSamplingDetails", "رمپ"))
        self.groupBoxSamplingDate.setTitle(_translate("DialogAddSamplingDetails", "تاریخ نمونه گیری"))
        self.comboBoxYear.setItemText(0, _translate("DialogAddSamplingDetails", "سال"))
        self.comboBoxYear.setItemText(1, _translate("DialogAddSamplingDetails", "1398"))
        self.comboBoxYear.setItemText(2, _translate("DialogAddSamplingDetails", "1399"))
        self.comboBoxYear.setItemText(3, _translate("DialogAddSamplingDetails", "1400"))
        self.comboBoxYear.setItemText(4, _translate("DialogAddSamplingDetails", "1401"))
        self.comboBoxYear.setItemText(5, _translate("DialogAddSamplingDetails", "1402"))
        self.comboBoxYear.setItemText(6, _translate("DialogAddSamplingDetails", "1403"))
        self.comboBoxYear.setItemText(7, _translate("DialogAddSamplingDetails", "1404"))
        self.comboBoxYear.setItemText(8, _translate("DialogAddSamplingDetails", "1405"))
        self.comboBoxYear.setItemText(9, _translate("DialogAddSamplingDetails", "1406"))
        self.comboBoxYear.setItemText(10, _translate("DialogAddSamplingDetails", "1407"))
        self.comboBoxYear.setItemText(11, _translate("DialogAddSamplingDetails", "1408"))
        self.comboBoxYear.setItemText(12, _translate("DialogAddSamplingDetails", "1409"))
        self.comboBoxYear.setItemText(13, _translate("DialogAddSamplingDetails", "1410"))
        self.comboBoxMount.setItemText(0, _translate("DialogAddSamplingDetails", "ماه"))
        self.comboBoxDay.setItemText(0, _translate("DialogAddSamplingDetails", "روز"))
        self.groupBoxMaterialProperties.setTitle(_translate("DialogAddSamplingDetails", "مشخصات مصالح"))
        self.comboBoxCementType.setItemText(1, _translate("DialogAddSamplingDetails", "I"))
        self.comboBoxCementType.setItemText(2, _translate("DialogAddSamplingDetails", "II"))
        self.comboBoxCementType.setItemText(3, _translate("DialogAddSamplingDetails", "III"))
        self.comboBoxCementType.setItemText(4, _translate("DialogAddSamplingDetails", "IV"))
        self.comboBoxCementType.setItemText(5, _translate("DialogAddSamplingDetails", "V"))
        self.label_fc.setText(_translate("DialogAddSamplingDetails", "مقاومت مشخصه"))
        self.labelCementType.setText(_translate("DialogAddSamplingDetails", "نوع سیمان"))
        self.labelUnit.setText(_translate("DialogAddSamplingDetails", "برحسب کیلوگرم بر سانتیمتر مربع"))
        self.labelType.setText(_translate("DialogAddSamplingDetails", "تیپ"))
        self.pushButtonCreateSampling.setText(_translate("DialogAddSamplingDetails", "ایجاد"))
        self.pushButtonCancelSampling.setText(_translate("DialogAddSamplingDetails", "لغو"))
import ImageIcons_rc
