# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditProjectDetails.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEditProjectDetails(object):
    def setupUi(self, DialogEditProjectDetails):
        DialogEditProjectDetails.setObjectName("DialogEditProjectDetails")
        DialogEditProjectDetails.resize(390, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogEditProjectDetails.sizePolicy().hasHeightForWidth())
        DialogEditProjectDetails.setSizePolicy(sizePolicy)
        DialogEditProjectDetails.setMinimumSize(QtCore.QSize(390, 290))
        DialogEditProjectDetails.setMaximumSize(QtCore.QSize(390, 290))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        DialogEditProjectDetails.setFont(font)
        DialogEditProjectDetails.setFocusPolicy(QtCore.Qt.NoFocus)
        DialogEditProjectDetails.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.labelContractNumber = QtWidgets.QLabel(DialogEditProjectDetails)
        self.labelContractNumber.setGeometry(QtCore.QRect(320, 20, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelContractNumber.sizePolicy().hasHeightForWidth())
        self.labelContractNumber.setSizePolicy(sizePolicy)
        self.labelContractNumber.setMinimumSize(QtCore.QSize(60, 30))
        self.labelContractNumber.setMaximumSize(QtCore.QSize(70, 30))
        self.labelContractNumber.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelContractNumber.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelContractNumber.setObjectName("labelContractNumber")
        self.labelProjectName = QtWidgets.QLabel(DialogEditProjectDetails)
        self.labelProjectName.setGeometry(QtCore.QRect(320, 58, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProjectName.sizePolicy().hasHeightForWidth())
        self.labelProjectName.setSizePolicy(sizePolicy)
        self.labelProjectName.setMinimumSize(QtCore.QSize(60, 30))
        self.labelProjectName.setMaximumSize(QtCore.QSize(60, 30))
        self.labelProjectName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelProjectName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelProjectName.setObjectName("labelProjectName")
        self.labelClient = QtWidgets.QLabel(DialogEditProjectDetails)
        self.labelClient.setGeometry(QtCore.QRect(320, 96, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelClient.sizePolicy().hasHeightForWidth())
        self.labelClient.setSizePolicy(sizePolicy)
        self.labelClient.setMinimumSize(QtCore.QSize(60, 30))
        self.labelClient.setMaximumSize(QtCore.QSize(60, 30))
        self.labelClient.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelClient.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelClient.setObjectName("labelClient")
        self.labelSupervisor = QtWidgets.QLabel(DialogEditProjectDetails)
        self.labelSupervisor.setGeometry(QtCore.QRect(320, 134, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSupervisor.sizePolicy().hasHeightForWidth())
        self.labelSupervisor.setSizePolicy(sizePolicy)
        self.labelSupervisor.setMinimumSize(QtCore.QSize(60, 30))
        self.labelSupervisor.setMaximumSize(QtCore.QSize(60, 30))
        self.labelSupervisor.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelSupervisor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSupervisor.setObjectName("labelSupervisor")
        self.labelAddress = QtWidgets.QLabel(DialogEditProjectDetails)
        self.labelAddress.setGeometry(QtCore.QRect(320, 210, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAddress.sizePolicy().hasHeightForWidth())
        self.labelAddress.setSizePolicy(sizePolicy)
        self.labelAddress.setMinimumSize(QtCore.QSize(60, 30))
        self.labelAddress.setMaximumSize(QtCore.QSize(60, 30))
        self.labelAddress.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAddress.setObjectName("labelAddress")
        self.pushButtonEditProject = QtWidgets.QPushButton(DialogEditProjectDetails)
        self.pushButtonEditProject.setGeometry(QtCore.QRect(50, 248, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEditProject.sizePolicy().hasHeightForWidth())
        self.pushButtonEditProject.setSizePolicy(sizePolicy)
        self.pushButtonEditProject.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonEditProject.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonEditProject.setObjectName("pushButtonEditProject")
        self.pushButtonCancel = QtWidgets.QPushButton(DialogEditProjectDetails)
        self.pushButtonCancel.setGeometry(QtCore.QRect(180, 248, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCancel.sizePolicy().hasHeightForWidth())
        self.pushButtonCancel.setSizePolicy(sizePolicy)
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.labelLabratory = QtWidgets.QLabel(DialogEditProjectDetails)
        self.labelLabratory.setGeometry(QtCore.QRect(320, 172, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLabratory.sizePolicy().hasHeightForWidth())
        self.labelLabratory.setSizePolicy(sizePolicy)
        self.labelLabratory.setMinimumSize(QtCore.QSize(60, 30))
        self.labelLabratory.setMaximumSize(QtCore.QSize(60, 30))
        self.labelLabratory.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelLabratory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLabratory.setObjectName("labelLabratory")
        self.lineEditContractNumber = QtWidgets.QLineEdit(DialogEditProjectDetails)
        self.lineEditContractNumber.setGeometry(QtCore.QRect(20, 20, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditContractNumber.sizePolicy().hasHeightForWidth())
        self.lineEditContractNumber.setSizePolicy(sizePolicy)
        self.lineEditContractNumber.setMinimumSize(QtCore.QSize(290, 30))
        self.lineEditContractNumber.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditContractNumber.setFont(font)
        self.lineEditContractNumber.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditContractNumber.setObjectName("lineEditContractNumber")
        self.lineEditProjectName = QtWidgets.QLineEdit(DialogEditProjectDetails)
        self.lineEditProjectName.setGeometry(QtCore.QRect(20, 58, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditProjectName.sizePolicy().hasHeightForWidth())
        self.lineEditProjectName.setSizePolicy(sizePolicy)
        self.lineEditProjectName.setMinimumSize(QtCore.QSize(290, 30))
        self.lineEditProjectName.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditProjectName.setFont(font)
        self.lineEditProjectName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditProjectName.setObjectName("lineEditProjectName")
        self.lineEditClient = QtWidgets.QLineEdit(DialogEditProjectDetails)
        self.lineEditClient.setGeometry(QtCore.QRect(20, 96, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditClient.sizePolicy().hasHeightForWidth())
        self.lineEditClient.setSizePolicy(sizePolicy)
        self.lineEditClient.setMinimumSize(QtCore.QSize(290, 30))
        self.lineEditClient.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditClient.setFont(font)
        self.lineEditClient.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditClient.setObjectName("lineEditClient")
        self.lineEditSupervisor = QtWidgets.QLineEdit(DialogEditProjectDetails)
        self.lineEditSupervisor.setGeometry(QtCore.QRect(20, 134, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSupervisor.sizePolicy().hasHeightForWidth())
        self.lineEditSupervisor.setSizePolicy(sizePolicy)
        self.lineEditSupervisor.setMinimumSize(QtCore.QSize(290, 30))
        self.lineEditSupervisor.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditSupervisor.setFont(font)
        self.lineEditSupervisor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditSupervisor.setObjectName("lineEditSupervisor")
        self.lineEditLabratory = QtWidgets.QLineEdit(DialogEditProjectDetails)
        self.lineEditLabratory.setGeometry(QtCore.QRect(20, 172, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditLabratory.sizePolicy().hasHeightForWidth())
        self.lineEditLabratory.setSizePolicy(sizePolicy)
        self.lineEditLabratory.setMinimumSize(QtCore.QSize(290, 30))
        self.lineEditLabratory.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditLabratory.setFont(font)
        self.lineEditLabratory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditLabratory.setObjectName("lineEditLabratory")
        self.lineEditAddress = QtWidgets.QLineEdit(DialogEditProjectDetails)
        self.lineEditAddress.setGeometry(QtCore.QRect(20, 210, 290, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAddress.sizePolicy().hasHeightForWidth())
        self.lineEditAddress.setSizePolicy(sizePolicy)
        self.lineEditAddress.setMinimumSize(QtCore.QSize(290, 30))
        self.lineEditAddress.setMaximumSize(QtCore.QSize(290, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAddress.setFont(font)
        self.lineEditAddress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditAddress.setObjectName("lineEditAddress")

        self.retranslateUi(DialogEditProjectDetails)
        QtCore.QMetaObject.connectSlotsByName(DialogEditProjectDetails)

    def retranslateUi(self, DialogEditProjectDetails):
        _translate = QtCore.QCoreApplication.translate
        DialogEditProjectDetails.setWindowTitle(_translate("DialogEditProjectDetails", "مشخصات پروژه"))
        self.labelContractNumber.setText(_translate("DialogEditProjectDetails", "شماره قرارداد"))
        self.labelProjectName.setText(_translate("DialogEditProjectDetails", "نام پروژه"))
        self.labelClient.setText(_translate("DialogEditProjectDetails", "کارفرما"))
        self.labelSupervisor.setText(_translate("DialogEditProjectDetails", "مشاور"))
        self.labelAddress.setText(_translate("DialogEditProjectDetails", "آدرس"))
        self.pushButtonEditProject.setText(_translate("DialogEditProjectDetails", "ویرایش پروژه"))
        self.pushButtonCancel.setText(_translate("DialogEditProjectDetails", "لغو"))
        self.labelLabratory.setText(_translate("DialogEditProjectDetails", "آزمایشگاه"))
