# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditSpecimenDetails.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEditSpecimenDetails(object):
    def setupUi(self, DialogEditSpecimenDetails):
        DialogEditSpecimenDetails.setObjectName("DialogEditSpecimenDetails")
        DialogEditSpecimenDetails.resize(250, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogEditSpecimenDetails.sizePolicy().hasHeightForWidth())
        DialogEditSpecimenDetails.setSizePolicy(sizePolicy)
        DialogEditSpecimenDetails.setMinimumSize(QtCore.QSize(250, 350))
        DialogEditSpecimenDetails.setMaximumSize(QtCore.QSize(250, 350))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        DialogEditSpecimenDetails.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ImageIcons/Icons/7740592.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogEditSpecimenDetails.setWindowIcon(icon)
        DialogEditSpecimenDetails.setLayoutDirection(QtCore.Qt.RightToLeft)
        DialogEditSpecimenDetails.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.labelManualSpecimenID = QtWidgets.QLabel(DialogEditSpecimenDetails)
        self.labelManualSpecimenID.setGeometry(QtCore.QRect(180, 10, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelManualSpecimenID.sizePolicy().hasHeightForWidth())
        self.labelManualSpecimenID.setSizePolicy(sizePolicy)
        self.labelManualSpecimenID.setMinimumSize(QtCore.QSize(70, 25))
        self.labelManualSpecimenID.setMaximumSize(QtCore.QSize(70, 25))
        self.labelManualSpecimenID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelManualSpecimenID.setObjectName("labelManualSpecimenID")
        self.lineEditManualSpecimenID = QtWidgets.QLineEdit(DialogEditSpecimenDetails)
        self.lineEditManualSpecimenID.setGeometry(QtCore.QRect(10, 10, 160, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditManualSpecimenID.sizePolicy().hasHeightForWidth())
        self.lineEditManualSpecimenID.setSizePolicy(sizePolicy)
        self.lineEditManualSpecimenID.setMinimumSize(QtCore.QSize(160, 25))
        self.lineEditManualSpecimenID.setMaximumSize(QtCore.QSize(160, 25))
        self.lineEditManualSpecimenID.setObjectName("lineEditManualSpecimenID")
        self.groupBoxMoldShapeProperties = QtWidgets.QGroupBox(DialogEditSpecimenDetails)
        self.groupBoxMoldShapeProperties.setGeometry(QtCore.QRect(0, 40, 250, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMoldShapeProperties.sizePolicy().hasHeightForWidth())
        self.groupBoxMoldShapeProperties.setSizePolicy(sizePolicy)
        self.groupBoxMoldShapeProperties.setMinimumSize(QtCore.QSize(250, 130))
        self.groupBoxMoldShapeProperties.setMaximumSize(QtCore.QSize(250, 130))
        self.groupBoxMoldShapeProperties.setObjectName("groupBoxMoldShapeProperties")
        self.groupBoxMoldShapeType = QtWidgets.QGroupBox(self.groupBoxMoldShapeProperties)
        self.groupBoxMoldShapeType.setGeometry(QtCore.QRect(10, 20, 230, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMoldShapeType.sizePolicy().hasHeightForWidth())
        self.groupBoxMoldShapeType.setSizePolicy(sizePolicy)
        self.groupBoxMoldShapeType.setMinimumSize(QtCore.QSize(230, 50))
        self.groupBoxMoldShapeType.setMaximumSize(QtCore.QSize(230, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBoxMoldShapeType.setFont(font)
        self.groupBoxMoldShapeType.setObjectName("groupBoxMoldShapeType")
        self.radioButtonCylindrical = QtWidgets.QRadioButton(self.groupBoxMoldShapeType)
        self.radioButtonCylindrical.setGeometry(QtCore.QRect(120, 18, 65, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonCylindrical.sizePolicy().hasHeightForWidth())
        self.radioButtonCylindrical.setSizePolicy(sizePolicy)
        self.radioButtonCylindrical.setMinimumSize(QtCore.QSize(65, 25))
        self.radioButtonCylindrical.setMaximumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.radioButtonCylindrical.setFont(font)
        self.radioButtonCylindrical.setObjectName("radioButtonCylindrical")
        self.radioButtonCubic = QtWidgets.QRadioButton(self.groupBoxMoldShapeType)
        self.radioButtonCubic.setGeometry(QtCore.QRect(20, 18, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonCubic.sizePolicy().hasHeightForWidth())
        self.radioButtonCubic.setSizePolicy(sizePolicy)
        self.radioButtonCubic.setMinimumSize(QtCore.QSize(60, 25))
        self.radioButtonCubic.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.radioButtonCubic.setFont(font)
        self.radioButtonCubic.setObjectName("radioButtonCubic")
        self.groupBoxMoldShapeSize = QtWidgets.QGroupBox(self.groupBoxMoldShapeProperties)
        self.groupBoxMoldShapeSize.setGeometry(QtCore.QRect(10, 70, 230, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMoldShapeSize.sizePolicy().hasHeightForWidth())
        self.groupBoxMoldShapeSize.setSizePolicy(sizePolicy)
        self.groupBoxMoldShapeSize.setMinimumSize(QtCore.QSize(230, 50))
        self.groupBoxMoldShapeSize.setMaximumSize(QtCore.QSize(230, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBoxMoldShapeSize.setFont(font)
        self.groupBoxMoldShapeSize.setObjectName("groupBoxMoldShapeSize")
        self.labelDimention = QtWidgets.QLabel(self.groupBoxMoldShapeSize)
        self.labelDimention.setGeometry(QtCore.QRect(110, 20, 80, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDimention.sizePolicy().hasHeightForWidth())
        self.labelDimention.setSizePolicy(sizePolicy)
        self.labelDimention.setMinimumSize(QtCore.QSize(80, 25))
        self.labelDimention.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.labelDimention.setFont(font)
        self.labelDimention.setText("")
        self.labelDimention.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDimention.setObjectName("labelDimention")
        self.comboBoxDimention = QtWidgets.QComboBox(self.groupBoxMoldShapeSize)
        self.comboBoxDimention.setGeometry(QtCore.QRect(20, 20, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDimention.sizePolicy().hasHeightForWidth())
        self.comboBoxDimention.setSizePolicy(sizePolicy)
        self.comboBoxDimention.setMinimumSize(QtCore.QSize(70, 25))
        self.comboBoxDimention.setMaximumSize(QtCore.QSize(70, 25))
        self.comboBoxDimention.setObjectName("comboBoxDimention")
        self.labelWieght = QtWidgets.QLabel(DialogEditSpecimenDetails)
        self.labelWieght.setGeometry(QtCore.QRect(90, 180, 150, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWieght.sizePolicy().hasHeightForWidth())
        self.labelWieght.setSizePolicy(sizePolicy)
        self.labelWieght.setMinimumSize(QtCore.QSize(150, 25))
        self.labelWieght.setMaximumSize(QtCore.QSize(150, 25))
        self.labelWieght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWieght.setObjectName("labelWieght")
        self.lineEditWieght = QtWidgets.QLineEdit(DialogEditSpecimenDetails)
        self.lineEditWieght.setGeometry(QtCore.QRect(10, 180, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWieght.sizePolicy().hasHeightForWidth())
        self.lineEditWieght.setSizePolicy(sizePolicy)
        self.lineEditWieght.setMinimumSize(QtCore.QSize(70, 25))
        self.lineEditWieght.setMaximumSize(QtCore.QSize(70, 25))
        self.lineEditWieght.setObjectName("lineEditWieght")
        self.labelTestDate = QtWidgets.QLabel(DialogEditSpecimenDetails)
        self.labelTestDate.setGeometry(QtCore.QRect(180, 220, 70, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTestDate.sizePolicy().hasHeightForWidth())
        self.labelTestDate.setSizePolicy(sizePolicy)
        self.labelTestDate.setMinimumSize(QtCore.QSize(70, 25))
        self.labelTestDate.setMaximumSize(QtCore.QSize(70, 25))
        self.labelTestDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTestDate.setObjectName("labelTestDate")
        self.comboBoxYearTestDate = QtWidgets.QComboBox(DialogEditSpecimenDetails)
        self.comboBoxYearTestDate.setGeometry(QtCore.QRect(10, 220, 65, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxYearTestDate.sizePolicy().hasHeightForWidth())
        self.comboBoxYearTestDate.setSizePolicy(sizePolicy)
        self.comboBoxYearTestDate.setMinimumSize(QtCore.QSize(65, 25))
        self.comboBoxYearTestDate.setMaximumSize(QtCore.QSize(65, 25))
        self.comboBoxYearTestDate.setObjectName("comboBoxYearTestDate")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxYearTestDate.addItem("")
        self.comboBoxMountTestDate = QtWidgets.QComboBox(DialogEditSpecimenDetails)
        self.comboBoxMountTestDate.setEnabled(False)
        self.comboBoxMountTestDate.setGeometry(QtCore.QRect(80, 220, 45, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMountTestDate.sizePolicy().hasHeightForWidth())
        self.comboBoxMountTestDate.setSizePolicy(sizePolicy)
        self.comboBoxMountTestDate.setMinimumSize(QtCore.QSize(45, 25))
        self.comboBoxMountTestDate.setMaximumSize(QtCore.QSize(45, 25))
        self.comboBoxMountTestDate.setObjectName("comboBoxMountTestDate")
        self.comboBoxMountTestDate.addItem("")
        self.comboBoxDayTestDate = QtWidgets.QComboBox(DialogEditSpecimenDetails)
        self.comboBoxDayTestDate.setEnabled(False)
        self.comboBoxDayTestDate.setGeometry(QtCore.QRect(130, 220, 45, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxDayTestDate.sizePolicy().hasHeightForWidth())
        self.comboBoxDayTestDate.setSizePolicy(sizePolicy)
        self.comboBoxDayTestDate.setMinimumSize(QtCore.QSize(45, 25))
        self.comboBoxDayTestDate.setMaximumSize(QtCore.QSize(45, 25))
        self.comboBoxDayTestDate.setObjectName("comboBoxDayTestDate")
        self.comboBoxDayTestDate.addItem("")
        self.labelUltimatForce = QtWidgets.QLabel(DialogEditSpecimenDetails)
        self.labelUltimatForce.setGeometry(QtCore.QRect(180, 265, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUltimatForce.sizePolicy().hasHeightForWidth())
        self.labelUltimatForce.setSizePolicy(sizePolicy)
        self.labelUltimatForce.setMinimumSize(QtCore.QSize(60, 25))
        self.labelUltimatForce.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUltimatForce.setFont(font)
        self.labelUltimatForce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelUltimatForce.setObjectName("labelUltimatForce")
        self.lineEditUltimatForce = QtWidgets.QLineEdit(DialogEditSpecimenDetails)
        self.lineEditUltimatForce.setGeometry(QtCore.QRect(60, 265, 115, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUltimatForce.sizePolicy().hasHeightForWidth())
        self.lineEditUltimatForce.setSizePolicy(sizePolicy)
        self.lineEditUltimatForce.setMinimumSize(QtCore.QSize(115, 25))
        self.lineEditUltimatForce.setMaximumSize(QtCore.QSize(115, 25))
        self.lineEditUltimatForce.setObjectName("lineEditUltimatForce")
        self.labelUnitUltimatForce = QtWidgets.QLabel(DialogEditSpecimenDetails)
        self.labelUnitUltimatForce.setGeometry(QtCore.QRect(0, 262, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUnitUltimatForce.sizePolicy().hasHeightForWidth())
        self.labelUnitUltimatForce.setSizePolicy(sizePolicy)
        self.labelUnitUltimatForce.setMinimumSize(QtCore.QSize(60, 30))
        self.labelUnitUltimatForce.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setStrikeOut(False)
        self.labelUnitUltimatForce.setFont(font)
        self.labelUnitUltimatForce.setTextFormat(QtCore.Qt.AutoText)
        self.labelUnitUltimatForce.setAlignment(QtCore.Qt.AlignCenter)
        self.labelUnitUltimatForce.setWordWrap(True)
        self.labelUnitUltimatForce.setObjectName("labelUnitUltimatForce")
        self.pushButtonEditSpecimen = QtWidgets.QPushButton(DialogEditSpecimenDetails)
        self.pushButtonEditSpecimen.setGeometry(QtCore.QRect(25, 310, 90, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEditSpecimen.sizePolicy().hasHeightForWidth())
        self.pushButtonEditSpecimen.setSizePolicy(sizePolicy)
        self.pushButtonEditSpecimen.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButtonEditSpecimen.setMaximumSize(QtCore.QSize(90, 25))
        self.pushButtonEditSpecimen.setObjectName("pushButtonEditSpecimen")
        self.pushButtonCancelSpecimen = QtWidgets.QPushButton(DialogEditSpecimenDetails)
        self.pushButtonCancelSpecimen.setGeometry(QtCore.QRect(135, 310, 90, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCancelSpecimen.sizePolicy().hasHeightForWidth())
        self.pushButtonCancelSpecimen.setSizePolicy(sizePolicy)
        self.pushButtonCancelSpecimen.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButtonCancelSpecimen.setMaximumSize(QtCore.QSize(90, 25))
        self.pushButtonCancelSpecimen.setObjectName("pushButtonCancelSpecimen")

        self.retranslateUi(DialogEditSpecimenDetails)
        QtCore.QMetaObject.connectSlotsByName(DialogEditSpecimenDetails)

    def retranslateUi(self, DialogEditSpecimenDetails):
        _translate = QtCore.QCoreApplication.translate
        DialogEditSpecimenDetails.setWindowTitle(_translate("DialogEditSpecimenDetails", "ویرایش مشخصات نمونه"))
        self.labelManualSpecimenID.setText(_translate("DialogEditSpecimenDetails", "شماره نمونه"))
        self.groupBoxMoldShapeProperties.setTitle(_translate("DialogEditSpecimenDetails", "مشخصات قالب نمونه"))
        self.groupBoxMoldShapeType.setTitle(_translate("DialogEditSpecimenDetails", "نوع قالب"))
        self.radioButtonCylindrical.setText(_translate("DialogEditSpecimenDetails", "استوانه‌ای"))
        self.radioButtonCubic.setText(_translate("DialogEditSpecimenDetails", "مکعبی"))
        self.groupBoxMoldShapeSize.setTitle(_translate("DialogEditSpecimenDetails", "اندازه بعد اصلی قالب"))
        self.labelWieght.setText(_translate("DialogEditSpecimenDetails", "وزن نمونه (برحسب کیلوگرم)"))
        self.labelTestDate.setText(_translate("DialogEditSpecimenDetails", "تاریخ تست"))
        self.comboBoxYearTestDate.setItemText(0, _translate("DialogEditSpecimenDetails", "سال"))
        self.comboBoxYearTestDate.setItemText(1, _translate("DialogEditSpecimenDetails", "1398"))
        self.comboBoxYearTestDate.setItemText(2, _translate("DialogEditSpecimenDetails", "1399"))
        self.comboBoxYearTestDate.setItemText(3, _translate("DialogEditSpecimenDetails", "1400"))
        self.comboBoxYearTestDate.setItemText(4, _translate("DialogEditSpecimenDetails", "1401"))
        self.comboBoxYearTestDate.setItemText(5, _translate("DialogEditSpecimenDetails", "1402"))
        self.comboBoxYearTestDate.setItemText(6, _translate("DialogEditSpecimenDetails", "1403"))
        self.comboBoxYearTestDate.setItemText(7, _translate("DialogEditSpecimenDetails", "1404"))
        self.comboBoxYearTestDate.setItemText(8, _translate("DialogEditSpecimenDetails", "1405"))
        self.comboBoxYearTestDate.setItemText(9, _translate("DialogEditSpecimenDetails", "1406"))
        self.comboBoxYearTestDate.setItemText(10, _translate("DialogEditSpecimenDetails", "1407"))
        self.comboBoxYearTestDate.setItemText(11, _translate("DialogEditSpecimenDetails", "1408"))
        self.comboBoxYearTestDate.setItemText(12, _translate("DialogEditSpecimenDetails", "1409"))
        self.comboBoxYearTestDate.setItemText(13, _translate("DialogEditSpecimenDetails", "1410"))
        self.comboBoxMountTestDate.setItemText(0, _translate("DialogEditSpecimenDetails", "ماه"))
        self.comboBoxDayTestDate.setItemText(0, _translate("DialogEditSpecimenDetails", "روز"))
        self.labelUltimatForce.setText(_translate("DialogEditSpecimenDetails", "نیروی نهایی"))
        self.labelUnitUltimatForce.setText(_translate("DialogEditSpecimenDetails", "(کیلوگرم نیرو)"))
        self.pushButtonEditSpecimen.setText(_translate("DialogEditSpecimenDetails", "ویرایش نمونه"))
        self.pushButtonCancelSpecimen.setText(_translate("DialogEditSpecimenDetails", "لغو"))
import ImageIcons_rc
