# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpecimenWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSpecimenWindow(object):
    def setupUi(self, DialogSpecimenWindow):
        DialogSpecimenWindow.setObjectName("DialogSpecimenWindow")
        DialogSpecimenWindow.setEnabled(True)
        DialogSpecimenWindow.resize(500, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogSpecimenWindow.sizePolicy().hasHeightForWidth())
        DialogSpecimenWindow.setSizePolicy(sizePolicy)
        DialogSpecimenWindow.setMinimumSize(QtCore.QSize(500, 430))
        DialogSpecimenWindow.setMaximumSize(QtCore.QSize(500, 430))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        DialogSpecimenWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ImageIcons/Icons/Specimen.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogSpecimenWindow.setWindowIcon(icon)
        DialogSpecimenWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        DialogSpecimenWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.groupBoxVerification = QtWidgets.QGroupBox(DialogSpecimenWindow)
        self.groupBoxVerification.setGeometry(QtCore.QRect(9, 345, 480, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxVerification.sizePolicy().hasHeightForWidth())
        self.groupBoxVerification.setSizePolicy(sizePolicy)
        self.groupBoxVerification.setMinimumSize(QtCore.QSize(480, 80))
        self.groupBoxVerification.setMaximumSize(QtCore.QSize(478, 80))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        self.groupBoxVerification.setFont(font)
        self.groupBoxVerification.setObjectName("groupBoxVerification")
        self.labelSamplingStatus = QtWidgets.QLabel(self.groupBoxVerification)
        self.labelSamplingStatus.setGeometry(QtCore.QRect(420, 30, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSamplingStatus.sizePolicy().hasHeightForWidth())
        self.labelSamplingStatus.setSizePolicy(sizePolicy)
        self.labelSamplingStatus.setMinimumSize(QtCore.QSize(40, 40))
        self.labelSamplingStatus.setMaximumSize(QtCore.QSize(40, 40))
        self.labelSamplingStatus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelSamplingStatus.setLineWidth(1)
        self.labelSamplingStatus.setText("")
        self.labelSamplingStatus.setObjectName("labelSamplingStatus")
        self.label_min = QtWidgets.QLabel(self.groupBoxVerification)
        self.label_min.setGeometry(QtCore.QRect(290, 20, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min.sizePolicy().hasHeightForWidth())
        self.label_min.setSizePolicy(sizePolicy)
        self.label_min.setMinimumSize(QtCore.QSize(100, 20))
        self.label_min.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_min.setFont(font)
        self.label_min.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_min.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_min.setObjectName("label_min")
        self.label_mean = QtWidgets.QLabel(self.groupBoxVerification)
        self.label_mean.setGeometry(QtCore.QRect(65, 20, 120, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mean.sizePolicy().hasHeightForWidth())
        self.label_mean.setSizePolicy(sizePolicy)
        self.label_mean.setMinimumSize(QtCore.QSize(120, 20))
        self.label_mean.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_mean.setFont(font)
        self.label_mean.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_mean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_mean.setObjectName("label_mean")
        self.labelMean = QtWidgets.QLabel(self.groupBoxVerification)
        self.labelMean.setGeometry(QtCore.QRect(12, 17, 50, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMean.sizePolicy().hasHeightForWidth())
        self.labelMean.setSizePolicy(sizePolicy)
        self.labelMean.setMinimumSize(QtCore.QSize(50, 25))
        self.labelMean.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelMean.setFont(font)
        self.labelMean.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelMean.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelMean.setText("")
        self.labelMean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMean.setObjectName("labelMean")
        self.labelMin = QtWidgets.QLabel(self.groupBoxVerification)
        self.labelMin.setGeometry(QtCore.QRect(235, 17, 50, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMin.sizePolicy().hasHeightForWidth())
        self.labelMin.setSizePolicy(sizePolicy)
        self.labelMin.setMinimumSize(QtCore.QSize(50, 25))
        self.labelMin.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelMin.setFont(font)
        self.labelMin.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelMin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelMin.setText("")
        self.labelMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelMin.setObjectName("labelMin")
        self.labelExplain = QtWidgets.QLabel(self.groupBoxVerification)
        self.labelExplain.setGeometry(QtCore.QRect(12, 43, 400, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelExplain.sizePolicy().hasHeightForWidth())
        self.labelExplain.setSizePolicy(sizePolicy)
        self.labelExplain.setMinimumSize(QtCore.QSize(400, 30))
        self.labelExplain.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelExplain.setFont(font)
        self.labelExplain.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelExplain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelExplain.setText("")
        self.labelExplain.setAlignment(QtCore.Qt.AlignCenter)
        self.labelExplain.setObjectName("labelExplain")
        self.groupBoxOutputSpecimen = QtWidgets.QGroupBox(DialogSpecimenWindow)
        self.groupBoxOutputSpecimen.setEnabled(True)
        self.groupBoxOutputSpecimen.setGeometry(QtCore.QRect(10, 237, 480, 110))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxOutputSpecimen.sizePolicy().hasHeightForWidth())
        self.groupBoxOutputSpecimen.setSizePolicy(sizePolicy)
        self.groupBoxOutputSpecimen.setMinimumSize(QtCore.QSize(480, 110))
        self.groupBoxOutputSpecimen.setMaximumSize(QtCore.QSize(480, 110))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        self.groupBoxOutputSpecimen.setFont(font)
        self.groupBoxOutputSpecimen.setObjectName("groupBoxOutputSpecimen")
        self.label_Volume = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label_Volume.setGeometry(QtCore.QRect(405, 48, 65, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Volume.sizePolicy().hasHeightForWidth())
        self.label_Volume.setSizePolicy(sizePolicy)
        self.label_Volume.setMinimumSize(QtCore.QSize(65, 20))
        self.label_Volume.setMaximumSize(QtCore.QSize(65, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_Volume.setFont(font)
        self.label_Volume.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Volume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Volume.setObjectName("label_Volume")
        self.label_Gama = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label_Gama.setGeometry(QtCore.QRect(405, 76, 65, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Gama.sizePolicy().hasHeightForWidth())
        self.label_Gama.setSizePolicy(sizePolicy)
        self.label_Gama.setMinimumSize(QtCore.QSize(65, 20))
        self.label_Gama.setMaximumSize(QtCore.QSize(65, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_Gama.setFont(font)
        self.label_Gama.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Gama.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Gama.setObjectName("label_Gama")
        self.labelcm2 = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelcm2.setGeometry(QtCore.QRect(380, 20, 25, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelcm2.sizePolicy().hasHeightForWidth())
        self.labelcm2.setSizePolicy(sizePolicy)
        self.labelcm2.setMinimumSize(QtCore.QSize(25, 20))
        self.labelcm2.setMaximumSize(QtCore.QSize(25, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.labelcm2.setFont(font)
        self.labelcm2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelcm2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelcm2.setText("")
        self.labelcm2.setPixmap(QtGui.QPixmap(":/ImageIcons/Icons/cm2.png"))
        self.labelcm2.setScaledContents(True)
        self.labelcm2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelcm2.setObjectName("labelcm2")
        self.labelcm3 = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelcm3.setGeometry(QtCore.QRect(380, 46, 25, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelcm3.sizePolicy().hasHeightForWidth())
        self.labelcm3.setSizePolicy(sizePolicy)
        self.labelcm3.setMinimumSize(QtCore.QSize(25, 20))
        self.labelcm3.setMaximumSize(QtCore.QSize(25, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.labelcm3.setFont(font)
        self.labelcm3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelcm3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelcm3.setText("")
        self.labelcm3.setPixmap(QtGui.QPixmap(":/ImageIcons/Icons/cm3.png"))
        self.labelcm3.setScaledContents(True)
        self.labelcm3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelcm3.setObjectName("labelcm3")
        self.labelkgcm3 = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelkgcm3.setGeometry(QtCore.QRect(380, 69, 25, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelkgcm3.sizePolicy().hasHeightForWidth())
        self.labelkgcm3.setSizePolicy(sizePolicy)
        self.labelkgcm3.setMinimumSize(QtCore.QSize(25, 30))
        self.labelkgcm3.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.labelkgcm3.setFont(font)
        self.labelkgcm3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelkgcm3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelkgcm3.setText("")
        self.labelkgcm3.setPixmap(QtGui.QPixmap(":/ImageIcons/Icons/kg-m3.png"))
        self.labelkgcm3.setScaledContents(True)
        self.labelkgcm3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelkgcm3.setObjectName("labelkgcm3")
        self.line = QtWidgets.QFrame(self.groupBoxOutputSpecimen)
        self.line.setGeometry(QtCore.QRect(250, 20, 20, 81))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label3kgfcm2 = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label3kgfcm2.setGeometry(QtCore.QRect(120, 70, 25, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3kgfcm2.sizePolicy().hasHeightForWidth())
        self.label3kgfcm2.setSizePolicy(sizePolicy)
        self.label3kgfcm2.setMinimumSize(QtCore.QSize(25, 30))
        self.label3kgfcm2.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.label3kgfcm2.setFont(font)
        self.label3kgfcm2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label3kgfcm2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3kgfcm2.setText("")
        self.label3kgfcm2.setPixmap(QtGui.QPixmap(":/ImageIcons/Icons/kgf-cm2.png"))
        self.label3kgfcm2.setScaledContents(True)
        self.label3kgfcm2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3kgfcm2.setObjectName("label3kgfcm2")
        self.label2kgfcm2 = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label2kgfcm2.setGeometry(QtCore.QRect(120, 42, 25, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2kgfcm2.sizePolicy().hasHeightForWidth())
        self.label2kgfcm2.setSizePolicy(sizePolicy)
        self.label2kgfcm2.setMinimumSize(QtCore.QSize(25, 30))
        self.label2kgfcm2.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.label2kgfcm2.setFont(font)
        self.label2kgfcm2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label2kgfcm2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2kgfcm2.setText("")
        self.label2kgfcm2.setPixmap(QtGui.QPixmap(":/ImageIcons/Icons/kgf-cm2.png"))
        self.label2kgfcm2.setScaledContents(True)
        self.label2kgfcm2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2kgfcm2.setObjectName("label2kgfcm2")
        self.labelVolume = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelVolume.setGeometry(QtCore.QRect(270, 48, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVolume.sizePolicy().hasHeightForWidth())
        self.labelVolume.setSizePolicy(sizePolicy)
        self.labelVolume.setMinimumSize(QtCore.QSize(100, 20))
        self.labelVolume.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelVolume.setFont(font)
        self.labelVolume.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelVolume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelVolume.setText("")
        self.labelVolume.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVolume.setObjectName("labelVolume")
        self.label_Area = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label_Area.setGeometry(QtCore.QRect(405, 22, 65, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Area.sizePolicy().hasHeightForWidth())
        self.label_Area.setSizePolicy(sizePolicy)
        self.label_Area.setMinimumSize(QtCore.QSize(65, 20))
        self.label_Area.setMaximumSize(QtCore.QSize(65, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(10)
        self.label_Area.setFont(font)
        self.label_Area.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Area.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Area.setObjectName("label_Area")
        self.labelArea = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelArea.setGeometry(QtCore.QRect(270, 20, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelArea.sizePolicy().hasHeightForWidth())
        self.labelArea.setSizePolicy(sizePolicy)
        self.labelArea.setMinimumSize(QtCore.QSize(100, 20))
        self.labelArea.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelArea.setFont(font)
        self.labelArea.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelArea.setText("")
        self.labelArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelArea.setObjectName("labelArea")
        self.labelGama = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelGama.setGeometry(QtCore.QRect(270, 76, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGama.sizePolicy().hasHeightForWidth())
        self.labelGama.setSizePolicy(sizePolicy)
        self.labelGama.setMinimumSize(QtCore.QSize(100, 20))
        self.labelGama.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelGama.setFont(font)
        self.labelGama.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelGama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelGama.setText("")
        self.labelGama.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGama.setObjectName("labelGama")
        self.label_StadardCompressionStrenght = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label_StadardCompressionStrenght.setGeometry(QtCore.QRect(150, 76, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_StadardCompressionStrenght.sizePolicy().hasHeightForWidth())
        self.label_StadardCompressionStrenght.setSizePolicy(sizePolicy)
        self.label_StadardCompressionStrenght.setMinimumSize(QtCore.QSize(100, 20))
        self.label_StadardCompressionStrenght.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_StadardCompressionStrenght.setFont(font)
        self.label_StadardCompressionStrenght.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_StadardCompressionStrenght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_StadardCompressionStrenght.setObjectName("label_StadardCompressionStrenght")
        self.labelStadardCompressionStrenght = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelStadardCompressionStrenght.setGeometry(QtCore.QRect(12, 76, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStadardCompressionStrenght.sizePolicy().hasHeightForWidth())
        self.labelStadardCompressionStrenght.setSizePolicy(sizePolicy)
        self.labelStadardCompressionStrenght.setMinimumSize(QtCore.QSize(100, 20))
        self.labelStadardCompressionStrenght.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelStadardCompressionStrenght.setFont(font)
        self.labelStadardCompressionStrenght.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelStadardCompressionStrenght.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelStadardCompressionStrenght.setText("")
        self.labelStadardCompressionStrenght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelStadardCompressionStrenght.setObjectName("labelStadardCompressionStrenght")
        self.label_CompressiveStrenght = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label_CompressiveStrenght.setGeometry(QtCore.QRect(150, 48, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CompressiveStrenght.sizePolicy().hasHeightForWidth())
        self.label_CompressiveStrenght.setSizePolicy(sizePolicy)
        self.label_CompressiveStrenght.setMinimumSize(QtCore.QSize(100, 20))
        self.label_CompressiveStrenght.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_CompressiveStrenght.setFont(font)
        self.label_CompressiveStrenght.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_CompressiveStrenght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CompressiveStrenght.setObjectName("label_CompressiveStrenght")
        self.labelCompressiveStrenght = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelCompressiveStrenght.setGeometry(QtCore.QRect(12, 48, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCompressiveStrenght.sizePolicy().hasHeightForWidth())
        self.labelCompressiveStrenght.setSizePolicy(sizePolicy)
        self.labelCompressiveStrenght.setMinimumSize(QtCore.QSize(100, 20))
        self.labelCompressiveStrenght.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelCompressiveStrenght.setFont(font)
        self.labelCompressiveStrenght.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelCompressiveStrenght.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCompressiveStrenght.setText("")
        self.labelCompressiveStrenght.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCompressiveStrenght.setObjectName("labelCompressiveStrenght")
        self.label_Age = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.label_Age.setGeometry(QtCore.QRect(120, 20, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Age.sizePolicy().hasHeightForWidth())
        self.label_Age.setSizePolicy(sizePolicy)
        self.label_Age.setMinimumSize(QtCore.QSize(100, 20))
        self.label_Age.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_Age.setFont(font)
        self.label_Age.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Age.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Age.setObjectName("label_Age")
        self.labelAge = QtWidgets.QLabel(self.groupBoxOutputSpecimen)
        self.labelAge.setGeometry(QtCore.QRect(12, 20, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAge.sizePolicy().hasHeightForWidth())
        self.labelAge.setSizePolicy(sizePolicy)
        self.labelAge.setMinimumSize(QtCore.QSize(100, 20))
        self.labelAge.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(11)
        self.labelAge.setFont(font)
        self.labelAge.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelAge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelAge.setText("")
        self.labelAge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAge.setObjectName("labelAge")
        self.groupBoxInputSpecimen = QtWidgets.QGroupBox(DialogSpecimenWindow)
        self.groupBoxInputSpecimen.setGeometry(QtCore.QRect(10, 60, 480, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxInputSpecimen.sizePolicy().hasHeightForWidth())
        self.groupBoxInputSpecimen.setSizePolicy(sizePolicy)
        self.groupBoxInputSpecimen.setMinimumSize(QtCore.QSize(480, 180))
        self.groupBoxInputSpecimen.setMaximumSize(QtCore.QSize(480, 180))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        self.groupBoxInputSpecimen.setFont(font)
        self.groupBoxInputSpecimen.setObjectName("groupBoxInputSpecimen")
        self.pushButtonAddSpecimen = QtWidgets.QPushButton(self.groupBoxInputSpecimen)
        self.pushButtonAddSpecimen.setGeometry(QtCore.QRect(445, 30, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddSpecimen.sizePolicy().hasHeightForWidth())
        self.pushButtonAddSpecimen.setSizePolicy(sizePolicy)
        self.pushButtonAddSpecimen.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButtonAddSpecimen.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButtonAddSpecimen.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ImageIcons/Icons/7746730.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAddSpecimen.setIcon(icon1)
        self.pushButtonAddSpecimen.setIconSize(QtCore.QSize(19, 19))
        self.pushButtonAddSpecimen.setObjectName("pushButtonAddSpecimen")
        self.tableViewInputSpecimen = QtWidgets.QTableView(self.groupBoxInputSpecimen)
        self.tableViewInputSpecimen.setGeometry(QtCore.QRect(10, 20, 430, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewInputSpecimen.sizePolicy().hasHeightForWidth())
        self.tableViewInputSpecimen.setSizePolicy(sizePolicy)
        self.tableViewInputSpecimen.setMinimumSize(QtCore.QSize(430, 150))
        self.tableViewInputSpecimen.setMaximumSize(QtCore.QSize(430, 150))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.tableViewInputSpecimen.setFont(font)
        self.tableViewInputSpecimen.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableViewInputSpecimen.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableViewInputSpecimen.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableViewInputSpecimen.setObjectName("tableViewInputSpecimen")
        self.tableViewInputSpecimen.horizontalHeader().setHighlightSections(False)
        self.tableViewInputSpecimen.verticalHeader().setDefaultSectionSize(25)
        self.tableViewInputSpecimen.verticalHeader().setHighlightSections(False)
        self.pushButtonEditSpecimen = QtWidgets.QPushButton(self.groupBoxInputSpecimen)
        self.pushButtonEditSpecimen.setEnabled(False)
        self.pushButtonEditSpecimen.setGeometry(QtCore.QRect(445, 60, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEditSpecimen.sizePolicy().hasHeightForWidth())
        self.pushButtonEditSpecimen.setSizePolicy(sizePolicy)
        self.pushButtonEditSpecimen.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButtonEditSpecimen.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButtonEditSpecimen.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ImageIcons/Icons/7740592.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEditSpecimen.setIcon(icon2)
        self.pushButtonEditSpecimen.setIconSize(QtCore.QSize(19, 19))
        self.pushButtonEditSpecimen.setObjectName("pushButtonEditSpecimen")
        self.pushButtonDelSpecimen = QtWidgets.QPushButton(self.groupBoxInputSpecimen)
        self.pushButtonDelSpecimen.setEnabled(False)
        self.pushButtonDelSpecimen.setGeometry(QtCore.QRect(445, 90, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDelSpecimen.sizePolicy().hasHeightForWidth())
        self.pushButtonDelSpecimen.setSizePolicy(sizePolicy)
        self.pushButtonDelSpecimen.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButtonDelSpecimen.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButtonDelSpecimen.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ImageIcons/Icons/7744522.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDelSpecimen.setIcon(icon3)
        self.pushButtonDelSpecimen.setIconSize(QtCore.QSize(19, 19))
        self.pushButtonDelSpecimen.setObjectName("pushButtonDelSpecimen")
        self.labelfc = QtWidgets.QLabel(DialogSpecimenWindow)
        self.labelfc.setGeometry(QtCore.QRect(50, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelfc.sizePolicy().hasHeightForWidth())
        self.labelfc.setSizePolicy(sizePolicy)
        self.labelfc.setMinimumSize(QtCore.QSize(100, 20))
        self.labelfc.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.labelfc.setFont(font)
        self.labelfc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelfc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelfc.setText("")
        self.labelfc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelfc.setObjectName("labelfc")
        self.label_fc = QtWidgets.QLabel(DialogSpecimenWindow)
        self.label_fc.setGeometry(QtCore.QRect(155, 10, 90, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fc.sizePolicy().hasHeightForWidth())
        self.label_fc.setSizePolicy(sizePolicy)
        self.label_fc.setMinimumSize(QtCore.QSize(90, 20))
        self.label_fc.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_fc.setFont(font)
        self.label_fc.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_fc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fc.setObjectName("label_fc")
        self.labelSampingID = QtWidgets.QLabel(DialogSpecimenWindow)
        self.labelSampingID.setGeometry(QtCore.QRect(310, 10, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSampingID.sizePolicy().hasHeightForWidth())
        self.labelSampingID.setSizePolicy(sizePolicy)
        self.labelSampingID.setMinimumSize(QtCore.QSize(100, 20))
        self.labelSampingID.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.labelSampingID.setFont(font)
        self.labelSampingID.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelSampingID.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelSampingID.setText("")
        self.labelSampingID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSampingID.setObjectName("labelSampingID")
        self.label_SamplingID = QtWidgets.QLabel(DialogSpecimenWindow)
        self.label_SamplingID.setGeometry(QtCore.QRect(415, 10, 75, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SamplingID.sizePolicy().hasHeightForWidth())
        self.label_SamplingID.setSizePolicy(sizePolicy)
        self.label_SamplingID.setMinimumSize(QtCore.QSize(75, 20))
        self.label_SamplingID.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_SamplingID.setFont(font)
        self.label_SamplingID.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_SamplingID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SamplingID.setObjectName("label_SamplingID")
        self.label_SamplingDate = QtWidgets.QLabel(DialogSpecimenWindow)
        self.label_SamplingDate.setGeometry(QtCore.QRect(415, 37, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SamplingDate.sizePolicy().hasHeightForWidth())
        self.label_SamplingDate.setSizePolicy(sizePolicy)
        self.label_SamplingDate.setMinimumSize(QtCore.QSize(70, 20))
        self.label_SamplingDate.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_SamplingDate.setFont(font)
        self.label_SamplingDate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_SamplingDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SamplingDate.setObjectName("label_SamplingDate")
        self.labelSampingDate = QtWidgets.QLabel(DialogSpecimenWindow)
        self.labelSampingDate.setGeometry(QtCore.QRect(310, 37, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSampingDate.sizePolicy().hasHeightForWidth())
        self.labelSampingDate.setSizePolicy(sizePolicy)
        self.labelSampingDate.setMinimumSize(QtCore.QSize(100, 20))
        self.labelSampingDate.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.labelSampingDate.setFont(font)
        self.labelSampingDate.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelSampingDate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelSampingDate.setText("")
        self.labelSampingDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSampingDate.setObjectName("labelSampingDate")
        self.label1kgfcm2 = QtWidgets.QLabel(DialogSpecimenWindow)
        self.label1kgfcm2.setGeometry(QtCore.QRect(20, 5, 25, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1kgfcm2.sizePolicy().hasHeightForWidth())
        self.label1kgfcm2.setSizePolicy(sizePolicy)
        self.label1kgfcm2.setMinimumSize(QtCore.QSize(25, 30))
        self.label1kgfcm2.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        self.label1kgfcm2.setFont(font)
        self.label1kgfcm2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label1kgfcm2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1kgfcm2.setText("")
        self.label1kgfcm2.setPixmap(QtGui.QPixmap(":/ImageIcons/Icons/kgf-cm2.png"))
        self.label1kgfcm2.setScaledContents(True)
        self.label1kgfcm2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1kgfcm2.setObjectName("label1kgfcm2")
        self.label_cement_type = QtWidgets.QLabel(DialogSpecimenWindow)
        self.label_cement_type.setGeometry(QtCore.QRect(155, 37, 90, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cement_type.sizePolicy().hasHeightForWidth())
        self.label_cement_type.setSizePolicy(sizePolicy)
        self.label_cement_type.setMinimumSize(QtCore.QSize(90, 20))
        self.label_cement_type.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        self.label_cement_type.setFont(font)
        self.label_cement_type.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_cement_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cement_type.setObjectName("label_cement_type")
        self.labelCement_type = QtWidgets.QLabel(DialogSpecimenWindow)
        self.labelCement_type.setGeometry(QtCore.QRect(50, 37, 100, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCement_type.sizePolicy().hasHeightForWidth())
        self.labelCement_type.setSizePolicy(sizePolicy)
        self.labelCement_type.setMinimumSize(QtCore.QSize(100, 20))
        self.labelCement_type.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.labelCement_type.setFont(font)
        self.labelCement_type.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelCement_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCement_type.setText("")
        self.labelCement_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCement_type.setObjectName("labelCement_type")

        self.retranslateUi(DialogSpecimenWindow)
        QtCore.QMetaObject.connectSlotsByName(DialogSpecimenWindow)

    def retranslateUi(self, DialogSpecimenWindow):
        _translate = QtCore.QCoreApplication.translate
        DialogSpecimenWindow.setWindowTitle(_translate("DialogSpecimenWindow", "نمونه‌ها"))
        self.groupBoxVerification.setTitle(_translate("DialogSpecimenWindow", "وضعیت پذیرش نمونه‌ها"))
        self.label_min.setText(_translate("DialogSpecimenWindow", "کمترین مقاومت فشاری"))
        self.label_mean.setText(_translate("DialogSpecimenWindow", "میانگین مقاومت‌های فشاری"))
        self.groupBoxOutputSpecimen.setTitle(_translate("DialogSpecimenWindow", "نتایج خروجی هر نمونه"))
        self.label_Volume.setText(_translate("DialogSpecimenWindow", "حجم نمونه"))
        self.label_Gama.setText(_translate("DialogSpecimenWindow", "وزن مخصوص"))
        self.label_Area.setText(_translate("DialogSpecimenWindow", "مساحت بارگذاری"))
        self.label_StadardCompressionStrenght.setText(_translate("DialogSpecimenWindow", "مقاومت فشاری استاندارد"))
        self.label_CompressiveStrenght.setText(_translate("DialogSpecimenWindow", "مقاومت فشاری"))
        self.label_Age.setText(_translate("DialogSpecimenWindow", "سن نمونه (روز)"))
        self.groupBoxInputSpecimen.setTitle(_translate("DialogSpecimenWindow", "نمونه‌ها"))
        self.label_fc.setText(_translate("DialogSpecimenWindow", "مقاومت مشخصه بتن"))
        self.label_SamplingID.setText(_translate("DialogSpecimenWindow", "شناسه نمونه‌گیری"))
        self.label_SamplingDate.setText(_translate("DialogSpecimenWindow", "تاریخ نمونه‌گیری"))
        self.label_cement_type.setText(_translate("DialogSpecimenWindow", "نوع سیمان"))
import ImageIcons_rc
